name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build the solution
        run: dotnet build --no-restore --configuration Release

      # Step 5: Run Unit Tests
      - name: Run Unit Tests
        run: dotnet test test/RockPaperScissors.UnitTests/RockPaperScissors.Tests.csproj

      # Step 6: Run Integration Tests
      - name: Run Integration Tests
        run: dotnet test test/RockPaperScissors.IntegrationTests/RockPaperScissors.IntegrationTests.csproj
